name: Bug report
description: Report something that is not working properly
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear description of the issue plus anything else you would like to add
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshot/video
      description: A screenshot or video to help explain the issue (if applicable)
  - type: input
    attributes:
      label: Operating system
      description: The operating system you are seeing the issue on
      placeholder: Android 10, Windows 10, etc.
    validations:
      required: true
  - type: input
    attributes:
      label: Browser
      description: The browser you are seeing the issue on
      placeholder: Google Chrome 100, Safari 15, etc.
    validations:
      required: true
